# -*- coding: utf-8 -*-
"""
Analysed comparison data for the TMHCC Media & Entertainment deliverables.
All entries are grounded in the six wordings reviewed:
  TMHCC  = Tokio Marine HCC — Media & Music Combined (0526), MASTER wording, 15 sections
  TYSERS = Tysers "Focus" Combined 'All Risks' Media policy (capacity: Zurich Insurance plc), 9 sections
  YUTREE = Media & Entertainment by Yutree (capacity: AXA Insurance UK plc), 12 cover sections
  LIBERTY= Liberty Entertainment Combined Policy, 6 cover sections
  ALLIANZ= Allianz Entertainment "Complete" Policy, 8 cover sections (+Terrorism)
  E      = Fifth competitor — PENDING (to be supplied in a later instruction)
Column order everywhere: TMHCC, Tysers, Yutree, Liberty, Allianz, Wording E (pending)
Status keys: yes | partial | no | review | na | pending
"""

WORDINGS = [
    dict(key="tmhcc",  name="TMHCC",            full="Tokio Marine HCC — Media & Music Combined",
         insurer="Tokio Marine HCC", sections="15 sections (master/primary wording)",
         ref="TMHCC_Media_Combined_0526_FINAL_amended"),
    dict(key="tysers", name="Tysers (Zurich)",  full="Tysers \u201cFocus\u201d Combined \u2018All Risks\u2019 Media policy",
         insurer="Zurich Insurance plc (capacity)", sections="9 sections",
         ref="Tysers Media Policy V6.2"),
    dict(key="yutree", name="Yutree (AXA)",     full="Media & Entertainment by Yutree",
         insurer="AXA Insurance UK plc (capacity); Yutree Underwriting (MGA)", sections="12 cover sections",
         ref="Media and Entertainment by Yutree Policy Wording, March 2024"),
    dict(key="liberty",name="Liberty",          full="Liberty Entertainment Combined Policy",
         insurer="Liberty (Liberty Specialty Markets)", sections="6 cover sections",
         ref="Liberty Entertainment Combined Policy (final v1, 12.11.24)"),
    dict(key="allianz",name="Allianz",          full="Allianz Entertainment \u2018Complete\u2019 Policy",
         insurer="Allianz", sections="8 cover sections (+ Terrorism)",
         ref="Entertainment Complete (Allianz)"),
    dict(key="pending",name="Wording E",        full="Fifth competitor \u2014 PENDING",
         insurer="\u2014", sections="To be assessed", ref="Awaiting upload (later instruction)"),
]

COMPETITOR_KEYS = ["tysers", "yutree", "liberty", "allianz", "pending"]

# ---------------------------------------------------------------------------
# 1. SECTION-LEVEL MATRIX  (15 TMHCC sections + Personal Accident row)
#    tuple: (label, [tmhcc, tysers, yutree, liberty, allianz, pending], verdict, comment)
#    verdict: tmhcc | comp | equal | review
# ---------------------------------------------------------------------------
SECTION_ROWS = [
    ("S1 \u00b7 Business \u201cAll Risks\u201d (premises buildings & contents)",
     ["yes","yes","yes","yes","yes","pending"], "equal",
     "All five offer premises/contents material damage on an all-risks basis. Allianz and Liberty are property-led packages with very granular MD extensions; TMHCC consolidates IT/premises cover here."),
    ("S2 \u00b7 Property & Equipment \u201cAll Risks\u201d (production/entertainment equipment)",
     ["yes","yes","yes","partial","yes","pending"], "equal",
     "Owned and hired-in production/entertainment equipment. Tysers (S1 Production Property), Yutree (Production property), Allianz (S6 Specified All Risks). Liberty covers entertainment equipment via specified Schedule items rather than a dedicated all-risks section."),
    ("S3 \u00b7 Business Interruption \u201cAll Risks\u201d",
     ["yes","yes","yes","yes","yes","pending"], "comp",
     "All offer BI. Allianz is structurally broader \u2014 it splits Increased Cost of Working (S2a) and Book Debts (S3) into discrete sections. Confirm TMHCC S3 expressly covers ICOW/AICOW and book debts."),
    ("S4 \u00b7 Terrorism",
     ["yes","no","yes","yes","yes","pending"], "tmhcc",
     "TMHCC, Yutree, Liberty and Allianz provide terrorism cover. Tysers EXCLUDES terrorism (General Exclusion 6 applies to Sections 1,2,3,5) with no buy-back section \u2014 client would need standalone Pool Re."),
    ("S5 \u00b7 Employers\u2019 Liability",
     ["yes","yes","yes","yes","yes","pending"], "equal",
     "Statutory EL provided by all five (typically GBP 10m). Broadly equivalent."),
    ("S6 \u00b7 Public Liability",
     ["yes","yes","yes","yes","yes","pending"], "equal",
     "Provided by all. Competitors combine Public & Products into a single section; TMHCC splits Public (S6) and Products (S7)."),
    ("S7 \u00b7 Products Liability",
     ["yes","yes","yes","yes","yes","pending"], "equal",
     "Provided by all (combined with Public Liability in the four competitor wordings)."),
    ("S8 \u00b7 Money",
     ["yes","yes","yes","yes","yes","pending"], "equal",
     "Money cover provided by all five. Yutree combines Money with personal-accident assault."),
    ("S9 \u00b7 Goods in Transit",
     ["yes","no","yes","no","yes","pending"], "tmhcc",
     "TMHCC, Yutree (GIT section) and Allianz (S5 Own Goods in Transit) provide GIT. Tysers and Liberty provide Money only \u2014 no dedicated GIT section identified."),
    ("S10 \u00b7 Loss of Licence",
     ["yes","no","no","no","no","pending"], "tmhcc",
     "UNIQUE to TMHCC. Premises-licence loss cover under the Licensing Act 2003 \u2014 not offered by any competitor wording reviewed. Highly relevant for venues/festivals."),
    ("S11 \u00b7 Production Indemnity \u201cAll Risks\u201d",
     ["yes","yes","yes","no","no","pending"], "tmhcc",
     "TMHCC, Tysers (S5 Multimedia & Producers Indemnity) and Yutree (Production Indemnity) cover production costs / cast / negatives. Liberty and Allianz do NOT offer production indemnity."),
    ("S12 \u00b7 Media Liability / Professional Indemnity (E&O)",
     ["yes","yes","yes","no","no","pending"], "equal",
     "The heart of a media wording. TMHCC (S12), Tysers (S8 PI/E&O) and Yutree (PI-Media + PI-Events) all provide it \u2014 see detailed feature matrix. Liberty and Allianz provide NO media/PI/E&O cover."),
    ("S13 \u00b7 Commercial Legal Expenses",
     ["yes","no","no","no","no","pending"], "tmhcc",
     "UNIQUE to TMHCC (ARAG-style legal expenses). No competitor wording includes a legal-expenses section."),
    ("S14 \u00b7 Management Liability (D&O / EPL etc.)",
     ["yes","no","no","no","no","pending"], "tmhcc",
     "UNIQUE to TMHCC. No competitor wording includes management-liability cover."),
    ("S15 \u00b7 Cyber Liability (standalone)",
     ["yes","no","partial","no","no","pending"], "tmhcc",
     "UNIQUE \u2014 TMHCC \u2018CyberGuard\u2019 is a genuine standalone cyber policy (multimedia, security & privacy, privacy-regulatory, PCI DSS). Yutree offers a Computer Breakdown section only (first-party breakdown, not cyber liability). Others: none."),
    ("(+) Personal Accident & Business Travel",
     ["no","yes","partial","no","review","pending"], "comp",
     "GAP for TMHCC: no standalone PA/business-travel section in the 15-section structure. Tysers (S9 PA & Business Travel) is extensive; Yutree covers personal-accident assault within its Money/PA section. Allianz references a \u2018Personal Accident\u2019 section in its exclusions but it is not in the provided cover list (requires review)."),
]

# ---------------------------------------------------------------------------
# 2. MEDIA LIABILITY / PI FEATURE MATRIX (Section 12 deep dive)
#    Liberty & Allianz have NO media/PI -> 'no'
# ---------------------------------------------------------------------------
MEDIA_FEATURES = [
    ("Defamation / libel / slander / malicious falsehood",
     ["yes","yes","yes","no","no","pending"], "equal",
     "TMHCC and Yutree cover \u2018unintentional\u2019 defamation; Tysers covers unless the statement was known/ought-to-have-been-known to be defamatory. Broadly equivalent."),
    ("IP infringement \u2013 copyright / trademark / passing off",
     ["yes","yes","yes","no","no","pending"], "equal",
     "All three media wordings cover unintentional IP infringement incl. passing-off."),
    ("Patent infringement",
     ["no","yes","no","no","no","pending"], "comp",
     "Tysers (clause 8.9) expressly includes PATENT infringement within IP cover. TMHCC and Yutree EXCLUDE patents. TMHCC is sensibly more restrictive (patents are hard to underwrite)."),
    ("Breach of confidence / invasion of privacy",
     ["yes","yes","yes","no","no","pending"], "equal",
     "Covered by all three (TMHCC/Yutree on an \u2018unintentional\u2019 basis; Tysers clauses 8.11/8.12)."),
    ("Breach of professional duty / negligence / E&O",
     ["yes","yes","yes","no","no","pending"], "equal",
     "Core E&O. Covered by all three media wordings."),
    ("Dishonesty / fraud of employees (write-back)",
     ["yes","partial","yes","no","no","pending"], "equal",
     "TMHCC (Insuring Clause 1.l) and Yutree (Dishonesty & fraud cover) grant an express write-back for employee dishonesty; Tysers handles via its Criminal/Malicious Acts exclusion with an employee carve-out."),
    ("Defence costs payable IN ADDITION to the limit",
     ["yes","yes","yes","no","no","pending"], "equal",
     "All three pay defence costs in addition, with proportionate reduction once the limit is exceeded."),
    ("Territorial / jurisdiction scope",
     ["partial","yes","partial","no","no","pending"], "comp",
     "Tysers PI is WORLDWIDE. TMHCC limits cover to the Schedule Geographical Limits and EXCLUDES actions brought outside the stated Jurisdiction (default worldwide ex-US/Canada). Yutree is schedule-driven and restricts US/Canada exposure. Competitor (Tysers) broader."),
    ("Data-protection defence costs",
     ["yes","partial","no","no","no","pending"], "tmhcc",
     "TMHCC grants Data Protection Defence Costs (GBP 250k). Yutree EXCLUDES breach of data-protection law in its PI section; Tysers has statutory-defence costs but not DP-specific. TMHCC clearer/broader here."),
    ("Criminal / statutory prosecution defence costs",
     ["partial","yes","yes","no","no","pending"], "comp",
     "Tysers pays statutory defence costs (Bribery Act, Corporate Manslaughter, H&S at Work, CDM Regs \u2014 GBP 1m). Yutree pays Criminal Prosecution Defence Costs (GBP 250k). TMHCC S12 grants only Data-Protection defence costs (broader criminal cover sits in S13/S14)."),
    ("Reputation management / crisis-PR costs",
     ["yes","no","yes","no","no","pending"], "equal",
     "TMHCC and Yutree both grant Reputation Management costs (GBP 250k). Not identified in Tysers S8."),
    ("Withdrawal / alteration of content (incl. ASA/OFCOM)",
     ["yes","no","yes","no","no","pending"], "equal",
     "TMHCC and Yutree both grant Withdrawal of Content (GBP 250k) including ASA/OFCOM complaints. Not identified in Tysers."),
    ("Rectification / mitigation costs",
     ["yes","yes","yes","no","no","pending"], "equal",
     "All three pay rectification/mitigation costs that avert a larger claim (TMHCC Rectification; Tysers 8.14; Yutree Mitigation costs)."),
    ("Costs to PROSECUTE infringement of the insured\u2019s own IP",
     ["yes","no","yes","no","no","pending"], "equal",
     "TMHCC (GBP 25k) and Yutree (IP-rights prosecution) fund pursuit of the insured\u2019s own IP; subject to a supporting legal opinion. Not identified in Tysers."),
    ("Distributors & purchasers extension",
     ["no","yes","no","no","no","pending"], "comp",
     "Tysers (clause 8.7) extends indemnity to purchasers/co-producers/distributors of the insured\u2019s media material (up to 5x the limit). Not provided by TMHCC or Yutree."),
    ("Journalistic source-protection / challenge to subpoena",
     ["no","yes","no","no","no","pending"], "comp",
     "Tysers (clause 8.13) funds legal costs to challenge a subpoena requiring disclosure of a source. Not provided by TMHCC or Yutree \u2014 broker-sensitive for editorial/news clients."),
    ("Representation costs at investigations / inquiries",
     ["partial","yes","partial","no","no","pending"], "comp",
     "Tysers (8.15, GBP 25k) covers representation at official examinations/inquiries. TMHCC provides this only via Data-Protection defence; Yutree via Criminal-Prosecution defence."),
    ("Loss of documents",
     ["yes","yes","yes","no","no","pending"], "equal",
     "Covered by all three (TMHCC Insuring Clause; Tysers 8.10 GBP 1m; Yutree Loss of Documents, GBP 500 excess)."),
    ("Unintentional virus transmission",
     ["yes","yes","partial","no","no","pending"], "equal",
     "TMHCC (GBP 500k sub-limit, with targeted-virus write-back) and Tysers (8.16, GBP 250k) cover unintentional virus transmission to third parties. Yutree treats virus within its broader cyber exclusion."),
    ("Mergers & acquisitions / subsidiary auto-acquisition",
     ["yes","review","yes","no","no","pending"], "equal",
     "TMHCC and Yutree both auto-include newly created/acquired entities below a 20% turnover threshold, with notification above. Tysers position requires review."),
    ("Pollution write-back (negligent advice)",
     ["no","no","partial","no","no","pending"], "comp",
     "Yutree grants a limited pollution write-back where the cause is a specific act/error/omission of the insured. TMHCC and Tysers exclude pollution from PI."),
    ("Cyber/data general exclusion impact on PI cover",
     ["yes","yes","no","no","no","pending"], "tmhcc",
     "TMHCC\u2019s general cyber/date exclusion applies to Sections 1\u201311 ONLY, leaving S12 with bespoke virus/unauthorised-access cover; Tysers\u2019 Electronic-Risk exclusion is dis-applied to S8. Yutree\u2019s PI carries a BROAD cyber & data-protection exclusion that strips cyber-related PI."),
    ("Senior-counsel (KC) dispute-resolution clause",
     ["partial","review","yes","no","no","pending"], "comp",
     "Yutree includes a clear King\u2019s Counsel arbitration clause for defence/settlement disputes. TMHCC relies on a general mediation/dispute condition; Tysers requires review."),
]

# ---------------------------------------------------------------------------
# 3. GENERAL EXCLUSIONS COMPARISON
#    tuple:(exclusion, [statuses x6 meaning 'excluded?'], note)  using yes=excluded
# ---------------------------------------------------------------------------
GENERAL_EXCL = [
    ("War / nuclear / radioactive contamination",
     ["yes","yes","yes","yes","yes","pending"],
     "Standard market exclusion present in all wordings. Broadly equivalent."),
    ("Terrorism (property/BI)",
     ["partial","yes","partial","partial","partial","pending"],
     "TMHCC, Yutree, Liberty, Allianz write terrorism back via a dedicated Terrorism section; Tysers excludes terrorism outright (Sections 1,2,3,5) with no buy-back."),
    ("Pollution / contamination",
     ["yes","yes","yes","yes","yes","pending"],
     "Excluded by all with the usual sudden/accidental & defined-peril write-backs. Equivalent."),
    ("Asbestos",
     ["yes","partial","yes","yes","yes","pending"],
     "Tysers PI (S8) has a professional-duty WRITE-BACK (cover where asbestos liability arises from negligent advice, GBP 1m, ex-bodily-injury). TMHCC and Yutree exclude asbestos more strictly in PI."),
    ("Cyber / electronic risk (first-party damage & BI)",
     ["yes","yes","yes","yes","yes","pending"],
     "All exclude cyber-caused physical damage/BI. KEY DIFFERENCE: TMHCC dis-applies its cyber/date exclusion to Sections 12\u201315; Tysers dis-applies Electronic Risk to S8 PI. Yutree\u2019s PI carries a broad cyber/data exclusion."),
    ("Date recognition / data-processing failure",
     ["yes","yes","yes","yes","yes","pending"],
     "Standard \u2018millennium/date\u2019-style exclusion. Tysers dis-applies it to S8/S9. Equivalent in substance."),
    ("Communicable disease / pandemic",
     ["yes","no","review","review","review","pending"],
     "TMHCC carries a BROAD communicable-disease exclusion (applies notwithstanding all other terms). Not identified in Tysers general exclusions; Yutree/Liberty/Allianz require confirmation. TMHCC is more protected here (a deliberate restriction)."),
    ("Sanctions / trade restrictions",
     ["yes","yes","yes","yes","yes","pending"],
     "All carry a sanctions clause. TMHCC has both a Trading-Sanctions and an International-Sanctions clause. Equivalent."),
    ("Northern Ireland (civil commotion) / sonic bangs",
     ["review","yes","review","yes","yes","pending"],
     "Standard UK property-package carve-outs present in Tysers/Liberty/Allianz; TMHCC treatment within property sections requires confirmation."),
]

# ---------------------------------------------------------------------------
# 4. PI-SPECIFIC EXCLUSIONS COMPARISON (Media/PI sections only)
#    columns: TMHCC, Tysers, Yutree (others n/a)
# ---------------------------------------------------------------------------
PI_EXCL = [
    ("Contractual / assumed liability",
     ["yes","yes","yes","na","na","pending"],
     "Excluded by all, with the standard write-back for liability that would exist absent the contract. TMHCC: duty \u2018more onerous than common law/statute\u2019. Equivalent."),
    ("Deliberate / reckless / dishonest acts (with employee write-back)",
     ["yes","yes","yes","na","na","pending"],
     "All exclude deliberate/dishonest acts of the insured but write back dishonest acts of employees. Equivalent."),
    ("Bodily injury / property damage",
     ["yes","yes","yes","na","na","pending"],
     "Excluded unless arising from negligent publication/advice. Equivalent."),
    ("Fines / penalties / punitive damages",
     ["partial","review","review","na","na","pending"],
     "TMHCC excludes non-compensatory damages BUT writes back libel/slander/defamation awards and punitive damages where the law permits payment \u2014 a favourable, clearly-drafted carve-back. Competitor positions require review."),
    ("Prior known claims / circumstances",
     ["yes","yes","yes","na","na","pending"],
     "Excluded by all (claims-made hygiene). Equivalent."),
    ("Insolvency / financial failure of the insured",
     ["yes","review","review","na","na","pending"],
     "TMHCC expressly excludes claims arising from its own insolvency/liquidation. Competitor positions require review."),
    ("USA / Canada jurisdiction",
     ["yes","no","partial","na","na","pending"],
     "TMHCC excludes actions brought / governed outside the stated Jurisdiction (default ex-US/Canada). Tysers PI is WORLDWIDE (no such exclusion). Yutree restricts US/Canada exposure. Competitor (Tysers) broader."),
    ("Patent infringement",
     ["yes","no","yes","na","na","pending"],
     "TMHCC and Yutree exclude patents; Tysers covers patent infringement. TMHCC sensibly more restrictive."),
    ("Cyber act / breach of data-protection law (within PI)",
     ["no","no","yes","na","na","pending"],
     "Yutree\u2019s PI carries a broad cyber-act & data-protection-law exclusion. TMHCC instead grants bespoke cover (virus, unauthorised access, DP defence costs) \u2014 TMHCC broader/clearer."),
    ("Pollution / seepage",
     ["yes","yes","partial","na","na","pending"],
     "TMHCC and Tysers exclude pollution from PI; Yutree grants a limited write-back for the insured\u2019s own negligent act/error/omission."),
]

# ---------------------------------------------------------------------------
# 5. CONDITIONS / WARRANTIES / CLAIMS OBLIGATIONS
# ---------------------------------------------------------------------------
CONDITIONS = [
    ("Claim notification",
     "Express CONDITION PRECEDENT to liability \u2014 notify as soon as practicable (S1\u201311); S13 within 28 days; S12 claims-made notification during the period. Among the most protective drafting.",
     "Notification under Special Condition 1; S8 PI is claims-made.",
     "Claims-made; defined notification conditions for claims and claim circumstances.",
     "Forward every claim document immediately on receipt.",
     "Forward claim/notify in accordance with claims condition; potential proportionate remedy."),
    ("Basis of cover (PI/Media)",
     "S12 Media Liability is claims-made with Retroactive Date; defence-costs in addition.",
     "S8 PI/E&O claims-made; defence costs in addition; Excess does not apply to defence costs.",
     "PI-Media claims-made; retroactive date; defence costs in addition.",
     "n/a \u2014 no PI/media section.",
     "n/a \u2014 no PI/media section."),
    ("Reasonable precautions / cyber-security conditions",
     "S12 imposes detailed computer-security conditions (firewall, AV, password change every 60 days, encryption, logging, regular back-ups) and \u2018reasonable steps to avoid loss\u2019.",
     "Loss-of-documents condition requires back-ups at least every 7 days held off-site.",
     "Reasonable-precautions and security expectations apply.",
     "General \u2018your duties\u2019 / reasonable precautions section.",
     "Reasonable-precautions and maintenance conditions."),
    ("Change of control",
     "S12 cover ceases on a change of control unless notified and agreed by endorsement.",
     "Requires review.",
     "Addressed via subsidiary creation/acquisition cover.",
     "n/a (no PI).",
     "n/a (no PI)."),
    ("Premium payment",
     "S12 premium payment clause \u2014 60 days, with 15-day cancellation notice.",
     "Per policy/General Conditions.",
     "Premium-adjustment condition with cancellation rights.",
     "Standard cancellation section.",
     "Standard cancellation provisions."),
    ("Fair presentation (Insurance Act 2015)",
     "Duty of fair presentation applies (UK).",
     "Duty of fair presentation; Zurich data terms.",
     "Express duty of fair presentation.",
     "\u2018About this policy / your duties\u2019 \u2014 fair presentation.",
     "Fair-presentation conditions."),
    ("Defence / dispute resolution",
     "Insurer consent required (CP); general mediation/dispute condition (England & Wales).",
     "Insurer controls defence; consent to settle.",
     "Clear King\u2019s Counsel arbitration clause for defence/settlement disputes \u2014 strong drafting.",
     "Insurer conduct-of-claims rights.",
     "Insurer conduct-of-claims rights."),
]

# ---------------------------------------------------------------------------
# 6. KEY SUB-LIMITS WITHIN MEDIA / PI (limit comparison)
# ---------------------------------------------------------------------------
SUBLIMITS = [
    ("Primary limit of indemnity", "Per Schedule", "Per Schedule", "Per Schedule", "n/a", "n/a"),
    ("Virus transmission", "GBP 500,000", "GBP 250,000", "Within cyber exclusion", "n/a", "n/a"),
    ("Data-protection defence costs", "GBP 250,000", "\u2014", "Excluded", "n/a", "n/a"),
    ("Criminal / statutory defence costs", "\u2014 (DP only)", "GBP 1,000,000", "GBP 250,000", "n/a", "n/a"),
    ("Reputation management", "GBP 250,000", "\u2014", "GBP 250,000", "n/a", "n/a"),
    ("Withdrawal of content", "GBP 250,000", "\u2014", "GBP 250,000", "n/a", "n/a"),
    ("Pursue insured\u2019s own IP", "GBP 25,000", "\u2014", "Limit of indemnity", "n/a", "n/a"),
    ("Loss of documents", "Per Schedule", "GBP 1,000,000", "Limit (GBP 500 excess)", "n/a", "n/a"),
    ("Representation costs", "DP only", "GBP 25,000", "Within criminal defence", "n/a", "n/a"),
    ("Court attendance (per day)", "GBP 500 / GBP 250", "GBP 500 / GBP 250 (GBP 25k agg)", "Requires review", "n/a", "n/a"),
    ("Distributors & purchasers", "\u2014", "5x limit of indemnity", "\u2014", "n/a", "n/a"),
]

# ---------------------------------------------------------------------------
# 7. COMPETITOR PROFILES (competitor-by-competitor analysis)
# ---------------------------------------------------------------------------
COMPETITOR_PROFILES = {
 "tysers": dict(
   title="Tysers \u201cFocus\u201d Combined \u2018All Risks\u2019 Media (capacity: Zurich Insurance plc)",
   shape="9 sections: Production Property, Property Damage, BI, Money, Production (Multimedia & Producers Indemnity), EL, Public & Products, Professional Indemnity/E&O, Personal Accident & Business Travel.",
   strengths=[
     "PI/E&O (S8) is WORLDWIDE and notably broad \u2014 includes PATENT infringement, statutory defence costs (Bribery/Corporate Manslaughter/H&S/CDM, GBP 1m), Distributors & Purchasers extension (5x limit), journalistic source-protection costs (challenge to subpoena), and representation costs (GBP 25k).",
     "Extensive standalone Personal Accident & Business Travel section (S9).",
     "Loss of documents sub-limit GBP 1m.",
   ],
   gaps=[
     "No terrorism cover (excluded outright).",
     "No dedicated Goods in Transit section (Money only).",
     "No Loss of Licence, Legal Expenses, Management Liability or standalone Cyber.",
     "No Reputation-Management or Withdrawal-of-Content extension identified in PI.",
   ]),
 "yutree": dict(
   title="Media & Entertainment by Yutree (capacity: AXA Insurance UK plc)",
   shape="12 cover sections incl. Property, Production Property, Computer Breakdown, BI, Terrorism, EL, Public & Products, Money & PA assault, Goods in Transit, Production Indemnity, PI-Media and PI-Events.",
   strengths=[
     "Two PI sections (Media; and Events & Installations) \u2014 useful where the client runs live events.",
     "Strong PI extensions: Reputation Management (GBP 250k), Withdrawal of Content (GBP 250k), Criminal Prosecution Defence (GBP 250k), Mitigation, limited Pollution write-back, and a clear King\u2019s Counsel dispute-resolution clause.",
     "Standalone Computer Breakdown section; Goods in Transit section.",
   ],
   gaps=[
     "PI carries a BROAD cyber & data-protection-law exclusion (strips cyber-related PI and DP defence).",
     "Excludes patents.",
     "No Loss of Licence, Legal Expenses, Management Liability or standalone Cyber-liability section.",
   ]),
 "liberty": dict(
   title="Liberty Entertainment Combined Policy",
   shape="6 cover sections: Material Damage, Business Interruption, Terrorism, Money, Employer\u2019s Liability, Public & Products Liability.",
   strengths=[
     "Property-led wording with detailed Material-Damage extensions (e.g. removal to private home, capital additions, professional fees).",
     "Clear, well-structured general exclusions/conditions.",
   ],
   gaps=[
     "NO Media Liability / PI / E&O cover \u2014 not an errors-&-omissions wording.",
     "No Production Indemnity, Goods in Transit, Loss of Licence, Legal Expenses, Management Liability, Cyber or Personal Accident.",
   ]),
 "allianz": dict(
   title="Allianz Entertainment \u2018Complete\u2019 Policy",
   shape="8 cover sections (+Terrorism): Property Damage, BI, Increased Cost of Working, Book Debts, Money, Own Goods in Transit, Specified All Risks, EL, Public & Products.",
   strengths=[
     "Granular BI suite \u2014 Increased Cost of Working (S2a) and Book Debts (S3) as discrete sections.",
     "Mature property-package drafting (Specified All Risks, GIT).",
   ],
   gaps=[
     "NO Media Liability / PI / E&O cover.",
     "No Production Indemnity, Loss of Licence, Legal Expenses, Management Liability or standalone Cyber.",
     "Personal Accident referenced in exclusions but not in the provided cover list (requires review).",
   ]),
}

# ---------------------------------------------------------------------------
# 8. TMHCC STRENGTHS  /  WHERE COMPETITORS ARE BROADER
# ---------------------------------------------------------------------------
TMHCC_STRENGTHS = [
  ("Widest section count in the peer group", "The only wording reviewed offering all 15 sections in a single contract \u2014 a genuine \u2018one-stop\u2019 media & entertainment package."),
  ("Four sections no competitor offers", "Loss of Licence (S10), Commercial Legal Expenses (S13), Management Liability (S14) and a standalone Cyber-liability section (S15 CyberGuard) are unique to TMHCC across the peer group."),
  ("Standalone cyber that is genuine liability cover", "CyberGuard provides multimedia, security & privacy, privacy-regulatory defence & penalties and PCI DSS cover \u2014 not merely first-party computer breakdown."),
  ("Broad, well-extended Media Liability (S12)", "Wide \u2018any other civil liability\u2019 grant plus employee-dishonesty write-back, Data-Protection Defence Costs (GBP 250k), Reputation Management (GBP 250k), Withdrawal of Content (GBP 250k), IP-pursuit costs (GBP 25k) and M&A auto-acquisition."),
  ("Clean exclusion architecture", "The general cyber/date exclusion is dis-applied to Sections 12\u201315, so the liability sections are governed by their own bespoke terms \u2014 avoiding the \u2018silent-cyber strip\u2019 seen in a competitor PI section."),
  ("Favourable fines/penalties carve-back", "Non-compensatory damages are written back for libel/slander/defamation awards and for punitive damages where the law permits payment."),
  ("Protective, clearly-drafted claims architecture", "Claim notification is an express condition precedent; aggregation, retroactive date and territorial/jurisdiction terms are clearly defined."),
]

COMP_BROADER = [
  ("Worldwide PI territory (Tysers)", "Tysers PI/E&O is worldwide; TMHCC S12 is limited to the Schedule Geographical Limits and excludes actions brought outside the stated Jurisdiction."),
  ("Patent infringement (Tysers)", "Tysers covers patent infringement within IP; TMHCC (and Yutree) exclude it."),
  ("Statutory / criminal defence costs (Tysers & Yutree)", "Tysers funds Bribery/Corporate-Manslaughter/H&S/CDM defence (GBP 1m); Yutree funds criminal-prosecution defence (GBP 250k). TMHCC S12 funds only data-protection defence (broader criminal cover sits in S13/S14)."),
  ("Distributors & purchasers (Tysers)", "Tysers extends PI to purchasers/co-producers/distributors of the insured\u2019s media material (5x limit) \u2014 absent from TMHCC."),
  ("Journalistic source protection (Tysers)", "Tysers funds legal costs to challenge a subpoena requiring disclosure of a source \u2014 absent from TMHCC."),
  ("Personal Accident & Business Travel (Tysers; Yutree assault)", "Tysers has an extensive PA/business-travel section; Yutree covers PA assault. TMHCC has no PA section."),
  ("Granular BI heads (Allianz)", "Allianz splits Increased Cost of Working and Book Debts into discrete sections \u2014 a presentational advantage."),
  ("Standalone Computer Breakdown (Yutree)", "Yutree offers a dedicated computer-breakdown section; TMHCC consolidates IT breakdown within S1/S2 \u2014 confirm it is explicit."),
  ("Limited pollution write-back in PI (Yutree)", "Yutree grants a limited pollution write-back for the insured\u2019s own negligent act/error/omission."),
  ("KC dispute-resolution clause (Yutree)", "Yutree\u2019s clear King\u2019s Counsel arbitration clause for defence disputes is a drafting-clarity advantage."),
]

# ---------------------------------------------------------------------------
# 9. GAP-FILL RECOMMENDATIONS (Document 2)
# ---------------------------------------------------------------------------
GAPFILL = [
 dict(title="Add a Personal Accident & Business Travel extension/section",
   comp="Tysers (S9, extensive); Yutree (PA assault within Money/PA)",
   does="Tysers provides a full personal-accident and business-travel section (incl. directors/employees/visitors, family travel, assault); Yutree covers personal-accident assault.",
   tmhcc="No standalone PA / business-travel section within the 15-section structure.",
   gap="Entertainment clients (crew, artists, touring personnel) routinely expect PA/business-travel; its absence is visible on a section-by-section comparison.",
   action="Add new optional extension/section (PA & Business Travel) \u2014 capacity-permitting.",
   commercial="Closes a whole-section gap; lets TMHCC show a tick on a row two competitors win.",
   broker="Brokers can place crew/touring PA within the same contract.",
   uw="Medium \u2014 PA/travel is well-understood; control via benefit schedule, age limits, hazardous-activity carve-outs.",
   claims="Low\u2013medium; defined benefits cap exposure.",
   priority="High",
   legal="Confirm capacity/appetite for PA & travel; draft benefit schedule and assault definition."),
 dict(title="Offer a worldwide / US-Canada territory option for Media Liability",
   comp="Tysers (PI worldwide)",
   does="Tysers PI/E&O applies worldwide with no jurisdiction exclusion.",
   tmhcc="S12 limited to Schedule Geographical Limits; excludes actions brought/governed outside the stated Jurisdiction (default ex-US/Canada).",
   gap="Media clients with global digital distribution can be exposed to US/Canada actions; TMHCC\u2019s default looks narrower on the matrix.",
   action="Add an optional worldwide (incl. or excl. US/Canada) write-back to the Geographical Limits / Legal Action exclusion, rated accordingly.",
   commercial="Converts a \u2018partial\u2019 to a \u2018covered\u2019 for global clients without changing the default risk appetite.",
   broker="Brokers can quote global-distribution risks competitively.",
   uw="High if US/Canada included \u2014 price/sub-limit/higher excess; keep ex-US/Canada as default.",
   claims="Higher in US/Canada (costs, punitive). Control via defence-cost caps and consent.",
   priority="High",
   legal="Draft optional endorsement; confirm reinsurance treaty territory."),
 dict(title="Add a Distributors & Purchasers extension to Media Liability",
   comp="Tysers (clause 8.7, up to 5x limit)",
   does="Extends indemnity to purchasers/co-producers/distributors of the insured\u2019s media material, subject to control-of-defence and notice conditions.",
   tmhcc="No equivalent extension.",
   gap="Production/distribution clients expect their distribution chain to be protected.",
   action="Add an optional Distributors & Purchasers extension with a capped aggregate (e.g. a multiple of the limit) and clear conditions.",
   commercial="Strong differentiator for production-house clients.",
   broker="Supports media clients that license/distribute content.",
   uw="Medium \u2014 control via 36-month claim window, certificate, control-of-defence (mirror Tysers conditions).",
   claims="Medium; aggregate multiple must be capped.",
   priority="Medium",
   legal="Draft extension; confirm acceptable aggregate multiple."),
 dict(title="Broaden criminal / regulatory defence-costs in Media Liability (or signpost S13/S14)",
   comp="Tysers (statutory defence GBP 1m); Yutree (criminal prosecution defence GBP 250k)",
   does="Fund defence of statutory/criminal proceedings (Bribery, Corporate Manslaughter, H&S, CDM) arising from the business.",
   tmhcc="S12 funds only Data-Protection defence costs (GBP 250k); broader criminal/regulatory defence sits in S13 Legal Expenses and S14 Management Liability.",
   gap="On a section-by-section read of S12 alone, TMHCC looks narrower.",
   action="Either add a modest criminal/regulatory defence-costs extension to S12, or add an express cross-reference noting that statutory/criminal defence is provided under S13/S14.",
   commercial="Removes an apparent gap with minimal added exposure.",
   broker="Clarifies where the criminal-defence cover lives.",
   uw="Low\u2013medium \u2014 a clarifying cross-reference is essentially nil-cost.",
   claims="Low.",
   priority="Medium-High",
   legal="Confirm S13/S14 triggers; draft cross-reference wording."),
 dict(title="Add journalistic source-protection costs to Media Liability",
   comp="Tysers (clause 8.13)",
   does="Funds legal costs to challenge a subpoena/court order requiring disclosure of a source.",
   tmhcc="Not provided.",
   gap="Broker-sensitive for editorial, news and publishing clients.",
   action="Add a modest sub-limited source-protection costs extension (insurer consent; reasonable prospects test).",
   commercial="Distinctive, low-frequency, brand-positive cover.",
   broker="Differentiator for editorial/news clients.",
   uw="Low \u2014 small sub-limit; consent and prospects-of-success conditions.",
   claims="Low frequency.",
   priority="Medium",
   legal="Draft sub-limited extension."),
 dict(title="Add representation costs at investigations/inquiries to Media Liability",
   comp="Tysers (clause 8.15, GBP 25k)",
   does="Funds representation at official examinations/inquiries that could give rise to a claim.",
   tmhcc="Provided only via Data-Protection defence; otherwise absent.",
   gap="Regulators increasingly investigate content/advertising.",
   action="Add a sub-limited representation-costs extension (e.g. GBP 25k).",
   commercial="Cheap, visible enhancement.",
   broker="Useful for advertising/marketing clients (ASA/CMA).",
   uw="Low \u2014 small sub-limit.",
   claims="Low.",
   priority="Medium",
   legal="Draft sub-limited extension; align with S13/S14."),
 dict(title="Consider a limited asbestos / pollution professional-duty write-back in PI",
   comp="Tysers (asbestos professional-duty write-back, GBP 1m, ex-BI); Yutree (pollution write-back for own negligence)",
   does="Cover PI liability that arises purely from negligent professional advice touching asbestos/pollution \u2014 not the contamination itself.",
   tmhcc="S12 excludes asbestos and pollution outright.",
   gap="Genuine E&O exposures (e.g. negligent advice/specification) fall in the exclusion gap.",
   action="Consider a narrow, sub-limited write-back limited to negligent advice, expressly excluding bodily injury and the contamination itself.",
   commercial="Closes a defensible E&O gap without taking environmental risk.",
   broker="Helpful for consultancy/advisory media clients.",
   uw="Medium \u2014 ring-fence to negligent advice; exclude BI and clean-up.",
   claims="Medium; cap tightly.",
   priority="Medium",
   legal="Careful drafting essential \u2014 keep BI and contamination excluded."),
 dict(title="Adopt a King\u2019s Counsel dispute-resolution clause in Media Liability",
   comp="Yutree (KC clause)",
   does="On a defence/settlement dispute, the matter is referred to a mutually-agreed King\u2019s Counsel whose view binds both parties.",
   tmhcc="Relies on a general mediation/dispute condition.",
   gap="Drafting-clarity opportunity; reduces coverage friction.",
   action="Add a KC-determination clause to S12 defence/settlement provisions.",
   commercial="Signals fair-claims handling.",
   broker="Reassures clients on defence disputes.",
   uw="Low \u2014 procedural.",
   claims="Reduces dispute cost.",
   priority="Low-Medium",
   legal="Standard clause; confirm cost-allocation wording."),
 dict(title="Make Increased Cost of Working / Book Debts explicit in BI",
   comp="Allianz (S2a ICOW; S3 Book Debts)",
   does="Presents ICOW/AICOW and Book Debts as named, discrete cover heads.",
   tmhcc="BI cover exists (S3) but ICOW/book-debts may be implicit.",
   gap="Presentational \u2014 competitors show more named BI heads.",
   action="Confirm and, if needed, name ICOW/AICOW and book-debts heads expressly in S3.",
   commercial="Improves like-for-like BI presentation.",
   broker="Easier BI comparison at point of sale.",
   uw="Low \u2014 clarification, not broadening (if already covered).",
   claims="Neutral.",
   priority="Medium",
   legal="Confirm S3 scope; adjust headings only."),
 dict(title="Confirm/clarify computer-breakdown cover within S1/S2",
   comp="Yutree (standalone Computer Breakdown section)",
   does="Dedicated first-party computer-breakdown section.",
   tmhcc="IT/breakdown consolidated within S1/S2 (per prior drafting).",
   gap="Presentational \u2014 a competitor shows a named breakdown section.",
   action="Add an explicit \u2018computer/IT breakdown\u2019 sub-heading or signpost within S1/S2.",
   commercial="Removes a perceived gap.",
   broker="Clear answer to \u2018is breakdown covered?\u2019.",
   uw="Low \u2014 clarification.",
   claims="Neutral.",
   priority="Low-Medium",
   legal="Confirm breakdown is within S1/S2; add signpost."),
 dict(title="Add a defined term for \u2018Media Material\u2019",
   comp="Tysers (defines Media Material)",
   does="Defines the subject-matter of cover precisely.",
   tmhcc="Uses \u2018data, text, sounds, images or similar content\u2019 descriptively.",
   gap="Minor drafting-clarity opportunity.",
   action="Consider adding a \u2018Media Material\u2019 (or \u2018Content\u2019) definition.",
   commercial="Sharper wording.",
   broker="Clearer scope.",
   uw="Nil.",
   claims="Reduces ambiguity.",
   priority="Low",
   legal="Optional drafting polish."),
 dict(title="LEAVE UNCHANGED \u2014 patents, communicable disease and default US/Canada exclusion",
   comp="Tysers (patents, worldwide)",
   does="Tysers covers patents and is worldwide; some competitors omit a pandemic exclusion.",
   tmhcc="Excludes patents; carries a broad communicable-disease exclusion; default ex-US/Canada jurisdiction.",
   gap="These are deliberate, defensible restrictions \u2014 not true gaps.",
   action="Leave unchanged (offer US/Canada only as a rated option per rec. 2).",
   commercial="Protects portfolio profitability and reinsurance terms.",
   broker="Explain as disciplined underwriting, not a deficiency.",
   uw="Retaining these protects TMHCC \u2014 broadening would materially increase volatility.",
   claims="Patents and pandemics are high-severity/systemic.",
   priority="Low",
   legal="No change recommended; document rationale."),
]

EXCL_WRITEBACKS = [
  ("Asbestos (PI)", "Tysers", "Professional-duty write-back (GBP 1m, ex-BI)",
   "TMHCC excludes asbestos in PI", "Consider narrow negligent-advice write-back (ex-BI, ex-contamination)", "Medium"),
  ("Pollution (PI)", "Yutree", "Write-back for insured\u2019s own negligent act/error/omission",
   "TMHCC excludes pollution in PI", "Consider narrow negligent-advice write-back", "Medium"),
  ("USA/Canada jurisdiction (PI)", "Tysers", "No jurisdiction exclusion (worldwide)",
   "TMHCC excludes actions outside Jurisdiction (default ex-US/Canada)", "Offer rated worldwide/US-Canada option; keep default", "High"),
  ("Patent infringement (PI)", "Tysers", "Patents covered within IP",
   "TMHCC excludes patents", "At most a limited defence-costs write-back; otherwise leave excluded", "Low"),
  ("Cyber/data exclusion vs PI", "(TMHCC favourable)", "Yutree strips cyber-related PI",
   "TMHCC dis-applies cyber/date exclusion to S12\u201315", "No change \u2014 retain as a TMHCC strength", "n/a"),
  ("Fines/penalties (PI)", "(TMHCC favourable)", "TMHCC writes back defamation awards & permitted punitive",
   "TMHCC already favourable", "No change \u2014 retain", "n/a"),
]

METHOD_NOTES = [
  "All six wordings were parsed in full to text; coverage was compared by FUNCTION, not heading, because the wordings are structured differently.",
  "Section maps were taken from each policy\u2019s contents/insuring clauses; feature-level findings from the operative clauses, extensions, conditions and exclusions actually read.",
  "Where a clause could not be verified from the wording it is marked \u2018? requires review\u2019 rather than assumed.",
  "No cover has been invented; competitor marketing language has not been treated as cover.",
  "TMHCC is recorded as having a gap ONLY where at least one competitor genuinely provides broader, clearer or materially useful cover.",
  "Exclusions, limits, conditions, warranties and write-backs were reviewed in detail and are not softened.",
  "Liberty and Allianz are property/BI/liability combined packages and contain NO media/PI/E&O, production-indemnity, cyber-liability, legal-expenses or management-liability sections.",
  "Fifth competitor (Wording E) is shown as a PENDING placeholder column, to be completed when the wording is supplied.",
]

ASSUMPTIONS = [
  "Competitor names are used as supplied; \u2018capacity\u2019 insurers (Zurich for Tysers; AXA for Yutree) are noted from the wordings.",
  "Primary limits, excesses and any \u2018insured/not insured\u2019 section toggles are schedule-driven and were not supplied \u2014 section availability reflects the wording booklet only.",
  "Allianz\u2019s \u2018Personal Accident\u2019 section is referenced in its exclusions but not in the provided cover list \u2014 treated as \u2018requires review\u2019.",
  "Page/clause citations are available in the working text extracts and can be added on request.",
]
